[package]
name = "aoc_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
fxhash = "0.2.1"
itertools = "0.13.0"
mapcomp = "0.3.0"
# num = "0.4.3"
num-traits = "0.2.19"
regex = "1.11.1"
serde_json = "1.0.131"
# polars = "0.43.1"
